import React from 'react';
import { ShieldCheck, Lock, Database, CheckCircle } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

export function Fairness({ onNavigate }: { onNavigate: (page: string) => void }) {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold mb-4 flex items-center justify-center gap-3">
          <ShieldCheck className="w-10 h-10 text-primary" />
          Provably Fair
        </h1>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Our fairness system is verifiable and transparent. You can verify every game result 
          to ensure it was not manipulated.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
        <Card>
          <CardContent className="pt-6 text-center space-y-4">
            <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
              <Database className="w-6 h-6 text-primary" />
            </div>
            <h3 className="font-bold">Server Seed</h3>
            <p className="text-sm text-muted-foreground">
              Generated by our secure server. This is hashed before the game starts so we can't change it.
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6 text-center space-y-4">
            <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
              <Lock className="w-6 h-6 text-primary" />
            </div>
            <h3 className="font-bold">Client Seed</h3>
            <p className="text-sm text-muted-foreground">
              You can influence the result by changing your client seed. This ensures we don't know the result.
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6 text-center space-y-4">
            <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
              <CheckCircle className="w-6 h-6 text-primary" />
            </div>
            <h3 className="font-bold">Verifiable</h3>
            <p className="text-sm text-muted-foreground">
              Combine the seeds and hash them to verify the result matches exactly what happened.
            </p>
          </CardContent>
        </Card>
      </div>

      <Card className="mb-12">
        <CardHeader>
          <CardTitle>Verify Game</CardTitle>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="crash">
            <TabsList className="mb-4">
              <TabsTrigger value="crash">Crash</TabsTrigger>
              <TabsTrigger value="mines">Mines</TabsTrigger>
              <TabsTrigger value="slots">Slots</TabsTrigger>
              <TabsTrigger value="dice">Dice</TabsTrigger>
            </TabsList>
            <TabsContent value="crash" className="space-y-4">
              <div className="grid gap-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Server Seed</label>
                  <Input placeholder="Enter server seed..." />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Client Seed</label>
                  <Input placeholder="Enter client seed..." />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Nonce</label>
                  <Input placeholder="0" type="number" />
                </div>
                <Button>Verify Result</Button>
              </div>
            </TabsContent>
            <TabsContent value="mines">
               <div className="text-center py-8 text-muted-foreground">Mines verification logic calculator...</div>
            </TabsContent>
            <TabsContent value="slots">
               <div className="text-center py-8 text-muted-foreground">Slots verification logic calculator...</div>
            </TabsContent>
            <TabsContent value="dice">
               <div className="text-center py-8 text-muted-foreground">Dice verification logic calculator...</div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
      
      <div className="text-center">
        <Button variant="outline" onClick={() => onNavigate('landing')}>Back to Home</Button>
      </div>
    </div>
  );
}